[package]
name = "bigint-benchmark"
version = "0.5.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2024"
description = "Benchmarks for big integer implementations"
keywords = ["bigint", "bignum", "mathematics", "benchmark"]
categories = ["mathematics"]
license = "MIT"
repository = "https://github.com/tczajka/bigint-benchmark-rs"
homepage = "https://github.com/tczajka/bigint-benchmark-rs"
readme = "README.md"

[dependencies]
clap = { version = "4.6.2", features = ["cargo"] }
ibig = "=0.3.6"
num-bigint = "=0.5.1"
rug = "=1.30.0"
malachite = "=0.9.2"
dashu = "=0.5.0"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = "symbols"
codegen-units = 1
