name: Benchmark

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build (linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Install rug dependencies
        run: sudo apt-get install diffutils gcc m4 make

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary-linux
          path: target/release/bigint-benchmark

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary-macos
          path: target/release/bigint-benchmark

  build-windows:
    name: Build (windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            pacman-mirrors  
            diffutils
            m4
            make
            mingw-w64-x86_64-gcc
          path-type: inherit

      - name: Configure Rust
        run: |
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup default stable-x86_64-pc-windows-gnu
          rustup component add clippy
          rustup update

      - name: Lint with Clippy
        shell: msys2 {0}
        run: cargo clippy -- -D warnings

      - name: Build
        shell: msys2 {0}
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary-windows
          path: target/release/bigint-benchmark.exe

  benchmark-linux:
    strategy:
      matrix:
        include:
          - name: "e 100k"
            args: "--task e -n 100000"
          - name: "e 1M"
            args: "--task e -n 1000000"
          - name: "e 10M"
            args: "--task e -n 10000000"
          - name: "fib 10M"
            args: "--task fib -n 10000000"
          - name: "fib 100M"
            args: "--task fib -n 100000000"
          - name: "fib_hex 100M"
            args: "--task fib_hex -n 100000000"
    name: "Benchmark (linux): ${{ matrix.name }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    needs: build-linux

    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binary-linux

      - name: Set binary permissions
        run: sudo chmod +rwx ./bigint-benchmark

      - name: Run benchmark
        run: ./bigint-benchmark ${{ matrix.args }} --lib dashu --lib ibig --lib malachite --lib num-bigint --lib rug benchmark

  benchmark-macos:
    strategy:
      matrix:
        include:
          - name: "e 100k"
            args: "--task e -n 100000"
          - name: "e 1M"
            args: "--task e -n 1000000"
          - name: "e 10M"
            args: "--task e -n 10000000"
          - name: "fib 10M"
            args: "--task fib -n 10000000"
          - name: "fib 100M"
            args: "--task fib -n 100000000"
          - name: "fib_hex 100M"
            args: "--task fib_hex -n 100000000"
    name: "Benchmark (macOS): ${{ matrix.name }}"
    runs-on: macos-latest

    needs: build-macos

    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binary-macos

      - name: Set binary permissions
        run: sudo chmod +rwx ./bigint-benchmark

      - name: Run benchmark
        run: ./bigint-benchmark ${{ matrix.args }} --lib dashu --lib ibig --lib malachite --lib num-bigint --lib rug benchmark

  benchmark-windows:
    strategy:
      matrix:
        include:
          - name: "e 100k"
            args: "--task e -n 100000"
          - name: "e 1M"
            args: "--task e -n 1000000"
          - name: "e 10M"
            args: "--task e -n 10000000"
          - name: "fib 10M"
            args: "--task fib -n 10000000"
          - name: "fib 100M"
            args: "--task fib -n 100000000"
          - name: "fib_hex 100M"
            args: "--task fib_hex -n 100000000"
    name: "Benchmark (windows): ${{ matrix.name }}"
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    needs: build-windows

    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binary-windows

      - name: Run benchmark
        run: ./bigint-benchmark ${{ matrix.args }} --lib dashu --lib ibig --lib malachite --lib num-bigint --lib rug benchmark
