name: Benchmark

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Install rug dependencies
        run: sudo apt-get install diffutils gcc m4 make

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: target/release/bigint-benchmark

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Rust
        run: |
          rustup update
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup default stable-x86_64-pc-windows-gnu

      - name: Install rug dependencies
        run: |
          pacman -S pacman-mirrors
          pacman -S diffutils m4 make mingw-w64-x86_64-gcc

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary-win
          path: target/release/bigint-benchmark

  benchmark:
    strategy:
      matrix:
        include:
          - name: "e 100k"
            args: "--task e -n 100000"
          - name: "e 1M"
            args: "--task e -n 1000000"
          - name: "e 10M"
            args: "--task e -n 10000000"
          - name: "fib 10M"
            args: "--task fib -n 10000000"
          - name: "fib 100M"
            args: "--task fib -n 100000000"
          - name: "fib_hex 100M"
            args: "--task fib_hex -n 100000000"
    name: "Benchmark: ${{ matrix.name }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    needs: build-linux

    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Set binary permissions
        run: sudo chmod +rwx ./bigint-benchmark

      - name: Run benchmark
        run: ./bigint-benchmark ${{ matrix.args }} --lib dashu --lib ibig --lib malachite --lib num-bigint --lib rug benchmark
